### PR TITLE
Convert long (>28 chars) table names to shorter names

### PR DESCRIPTION
**Pull request by nadavkav**
block_configurable_reports_report > block_cr_report
block_configurable_reports_component > block_cr_component
block_configurable_reports_plugin > block_cr_plugin

(It is installed on a Moodle 2.3.1 system)

### CODE REVIEW

**Comment by jleyva** [comment]
Hi,

thanks for your pull request, but I already fixed this for make the plugin works in 2.3, see please:
https://github.com/jleyva/moodle-block_configurablereports/commit/80bfd288c9b7782c4c521b3217ca4f1711d07ba4
https://github.com/jleyva/moodle-block_configurablereports/commit/5798175ca080aa7d9650ac3b2e9797f4c4db3b2b
https://github.com/jleyva/moodle-block_configurablereports/commit/29dc8442f8210ddba0adf191b6a03245452b335a

Regards

**Comment by nadavkav** [comment]
Hi Juan,
Your updates seems to be related to Moodle 2.1 or 2.2 and refer only to one table.
In Moodle 2.3 you have two more tables that needs to be fixed.
And, i was using the MDL_23 branch and those changes were not commit on that branch. (Am i correct?)

**Comment by jleyva** [comment]
Hi,
I'm terrible sorry but I noticed you used an unstable version due to my fault for using a bad naming convention, the MOODLE_22_STABLE version is not stable at all, is a work in progress version with lot of bugs. The work is stopped because Moodle HQ is evaluating which report builder will be integrated in 2.4 or 2.5 so we are waiting the final decision 

I suggest you tu use MOODLE_21_STABLE instead, sorry again and thanks for your help

**Comment by nadavkav** [comment]
I am a heavy user of CR on Moodle 19 systems. I follow the http://tracker.moodle.org/browse/MDL-30193 report builder evaluation issue.
I am not waiting for their resolution, since i think CR is better for our needs. ( Our academic stuff will not build report they will only use reports we build for them. building reports is not something that can be done by regular academic stuff, to my experience. It is even a security risk in some cases) 

anyways...
Please tell me if you are working on a Moodle 23 version Or what is not yet available so i can continue the development.
( I have already made some patches to the Moodle 19 version i wish to migrate to Moodle 2+ , see the MDL-30193)

**Comment by jleyva** [comment]
Hello,

as far as I know the  MOODLE_21_STABLE version works in 2.3, you can download it from the moodle plugins database or from github (be sure you are in the  MOODLE_21_STABLE branch)

Regards

**Comment by jleyva** [comment]
I will try to explain myself better than in the previous comment.

If you want to add some features or apply patches to a stable version that works in 2.3 you should work in the MOODLE_21_STABLE, I'll very happy to integrate it in the plugin (I review the Moodle issue and I saw the improvements you made)

The MOODLE_22_STABLE is a development version that rewrites lots of parts of the code, we've stopped developing a few months ago. It's full of bugs and it's not suitable for production servers

**Comment by nadavkav** [comment]
Thank you for clarifying this! ( I am off to my summer break. but as soon as i am back... i will send you some pull request for the changes i made to MOODLE_21_STABLE branch which i migrated from my Moodle 19 servers)

**Pull request closed without merging**
