### PR TITLE
Fixes year filter

### PR DESCRIPTION
**Pull request by usernamenumber**
It looks like there was no code to generate a list of options for the year filter.

### CODE REVIEW

**Comment by jleyva** [comment]
Hi,
thanks for reporting this, I'm sorry for not integrated it later but I didn't receive notifications

We cannot add code logic in lang files in Moodle because AMOS (the moodle translation tool) will fail, you should fix this outside the lang file.

**Comment by usernamenumber** [comment]
Ok, that makes sense, but unless I'm misreading something the code that's currently in the repo [looks for a `filteryearnumeric_list`](https://github.com/jleyva/moodle-block_configurablereports/blob/CR_23_STABLE/components/filters/yearnumeric/plugin.class.php#L65) string, which doesn't even exist in the langs file. I'm running my patched version so I can't check what the resulting behavior is, but doesn't this create an empty dropdown list? It must be something odd, or I wouldn't have thought to fix it! ;)

**Comment by jleyva** [comment]
yes, you are right. I think this is a regressions caused by some external code I integrated

**Comment by nadavkav** [comment]
Me bad, it was originally PR by me with a hardcoded list of years ($string['filteryearnumeric_list'] = '2012,2013,...';) in numeric format. Your suggested solution looks, though I think we should have it start from a year that can be set by the user (admin) at the block's setting page. what do you think?

**Comment by sarjona** [comment]
Thanks for reporting and working on this.

It has been fixed in the commit d7eae87b9d92f73615cb0e7b60759ba00dea6da1

Instead of using the undeclared 'filteryearnumeric_list' string, the **get_min_year** and **get_max_year** functions from the calendar factory will be used.

**Pull request closed without merging**
