### PR TITLE
Issue with downloading a filtered report 

### PR DESCRIPTION
**Pull request by luukverhoeven**
- Resolves the issue where all data is downloaded instead of just the filtered data.

### CODE REVIEW

**Comment by luukverhoeven** [comment]
Hi @jleyva, we've identified an issue where all data, instead of just the filtered data, is being downloaded. Could you please review and approve the pull request? Thanks!

**Comment by rmartinez-c2** [comment]
Good morning. When are you planning to incorporate these changes into the version of the plugin published in moodle? We currently have our moodle away on a server that does not allow custom changes to the source code.

Thank you.

Regards.

**Comment by martingskillset** [comment]
Hi @jleyva - I can confirm that the issue 1 fix works - is there any chance this could be rolled up into a new version please?

**Comment by jleyva** [comment]
We will publish an updated version of the plugin with this fix once Moodle LMS 4.5 is released

**Comment by martingskillset** [comment]
Thank you - much appreciated.

**Pull request merged**
