### PR TITLE
Code style fixes

### PR DESCRIPTION
**Pull request by jamesmcq**
Fixed up the code style to match the Moodle coding style.

### CODE REVIEW

**Comment by jleyva** [comment]
Wow, that's a lot of code and refactors, thanks a lot!

I tried to maintain one unique version of the plugin compatible with Moodle 2.2 and onwards, but in you code I see that it seems to be compatible only for 2.7 and onwards.

Can you confirm if the code works for 2.7?

**Comment by jamesmcq** [comment]
Hi Juan,

I've based this off the CR_23_STABLE branch (which by the name would be M2.3+?). However, it does contain some short-array syntax, which is PHP5.4+ (which is supported by M2.7+), so yes M2.7+ would be safe for this. 

However I believe the short array syntax should be the only thing that may define M2.7+ if the CR_23_STABLE branch is designed to be M2.3+.

**Comment by jleyva** [comment]
Hi James,

thanks for your response, I will create a new stable branch for your code and maintain the code only for 2.7 and onwards.

I think I can send pull requests from your repo, if not, I will ask you to do that

Thanks again, Juan

**Comment by jleyva** [comment]
Done, please, if you do additional changes please base your work on https://github.com/jleyva/moodle-block_configurablereports/tree/CR_27_STABLE

**Pull request closed without merging**
