### PR TITLE
Moodle 35 stable

### PR DESCRIPTION
**Pull request by egiles**
Make the plugin compatible with Moodle 3.5 by adding GDPR API.
This should close issue #102

### CODE REVIEW

**Comment by danmarsden** [comment]
@jleyva - any chance of getting this merged in? - we've got a few clients that would like to use this in 3.5 but this is currently blocking their ability to use it.

**Comment by danmarsden** [comment]
hmm - I just looked at the code... it doesn't look ready to me - looks like it probably should have used the null provider class. @egiles are you able to tidy that up?

**Comment by danmarsden** [comment]
- I do see the class mentions that it sends messages, but I'm not sure if that is actually required in the privacy api class is it?

**Comment by egiles** [comment]
Hi @danmarsden 

I didn't actually write the code myself (only created the pull request...), however, the developer who wrote it says that the null provider isn't appropriate here because even though the plugin doesn't store user data, it does send emails to the users, and it needs to declare that.

Basically, he is saying that he thinks it is required in the privacy API class.

I really don't know :(

**Comment by danmarsden** [comment]
that doesn't appear to be documented in the moodle privacy api docs  - hopefully @jleyva can check in with the hq team to verify if it is needed.

**Comment by sarjona** [comment]
Hi Nathan! 

Thank you very much for working on this :-) And also thanks to Dan for reviewing the patch. I agree with you: the message system declares itself all the messages and notifications sent by all the components, so it's not needed to declare it as a subsystem in all the components sending messages.

However, as the plugin has the ownerid field in the table block_configurable_reports, we need to declare and export this information, and anonymise it when the user is removed. 

The following commit implements the Privacy API for this block from 3.3 onwards: 7b35af80074c702529ff15d518a8385647fcc1c8
In order to clean the tracker, as this issue has been fixed, I'm going to close it.

Thanks again for your contributions! :-)

**Pull request closed without merging**
